import { Metadata } from "next";
import Image from "next/image";
import Canvas from "../components/Canvas";
import styles from "../styles/Home.module.css";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "with-jotai",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className={styles.container}>
      <h1 className={styles.title}><a href="https://github.com/vercel/next.js/tree/canary/examples/with-jotai" target="_blank">With Jotai example</a></h1>
      <main className={styles.main}>
        <Canvas />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
